ARG SYSTEM_NAME='ubuntu'
ARG SYSTEM_VERSION="22.04"
ARG ORIGNAME=""
ARG PROJECTNAME=""
ARG BUILD_ARCH=""
FROM ${SYSTEM_NAME}:${SYSTEM_VERSION} as builder
RUN apt update
RUN apt install -y build-essential devscripts equivs
ARG PROJECTNAME
ARG ORIGNAME
COPY files/${ORIGNAME} /code/
COPY files/${PROJECTNAME} /code/${PROJECTNAME}/
WORKDIR /code/${PROJECTNAME}
RUN echo "y" | mk-build-deps -i
RUN rm *-build-deps*
ENV DEB_BUILD_OPTIONS nocheck
ARG BUILD_ARCH
RUN  dpkg-buildpackage -us -uc --target-arch ${BUILD_ARCH}

FROM scratch as buildinfo
COPY --from=builder /code/*.buildinfo /
