ARG SYSTEM_NAME='ubuntu'
ARG SYSTEM_VERSION="22.04"
ARG ORIGNAME=""
ARG BUILD_ARCH=""
FROM ${SYSTEM_NAME}:${SYSTEM_VERSION} AS builder
ARG SYSTEM_NAME
ARG SYSTEM_VERSION
RUN if [ "$SYSTEM_NAME" = "centos" ] && [ "$SYSTEM_VERSION" = "8" ]; then \
  sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*; \
fi
RUN if [ "$SYSTEM_NAME" = "centos" ] && [ "$SYSTEM_VERSION" = "8" ]; then \
  sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*; \
fi
RUN dnf clean all
RUN dnf makecache
RUN dnf install -y rpmdevtools 'dnf-command(builddep)'
ARG ORIGNAME
COPY files/${ORIGNAME} /code/
WORKDIR /code/
RUN dnf builddep -y ${ORIGNAME}
RUN rpmbuild -rb --nocheck --nodebuginfo ${ORIGNAME}

RUN for targetDir in /root/rpmbuild/RPMS/* ; do \
  for file in ${targetDir}/*.rpm ; do \
    echo "package:" >> /code/res.info ; rpm -qpi $file >> /code/res.info ; \
    echo "requires:" >> /code/res.info ; rpm -qpr $file >> /code/res.info ; \
    echo "provides:" >> /code/res.info ; rpm -qpP $file >> /code/res.info ; \
  done \
done

FROM scratch AS buildinfo
COPY --from=builder /code/res.info /
